seed: 2
model:
    arch: maple
    name: ViT-B/16 # available_models = ['RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px']
    prec: fp16 # choose between ["fp16", "fp32", "amp"]
    n_ctx: 2 # number of context vectors
    ctx_init: "a photo of a" 
    prompt_depth: 3
data:
    name: imagenet
    loader: HierDataLoader
    data_root: prepro/raw/imagenet
    train: prepro/data/imagenet/gt_train.txt
    test: prepro/data/imagenet/gt_test.txt
    hierarchy: prepro/data/imagenet/tree.npy

    batch_size: 2
    test_batch_size: 1024
    n_workers: 4
    sampler:
        name: nshot
        nshot: 16
    transform: clip

# what are the label set used for initialized the model (i.e. text encoder)
init_label_set: "leaf"

# refer to the following url for setting up the learning rate and optimization
# https://github.com/KaiyangZhou/CoOp/search?q=sgd
optim:
  name: "sgd"
  lr: 0.02
  max_epoch: 10
  lr_scheduler: "cosine"
  warmup_epoch: 1
  warmup_type: "constant"
  warmup_cons_lr: 0.001
  use_scheduler: True

# loss function
loss:
  name: "ce"

print_freq: 20
exp: ViT-B_16/few_shot/16_shot/MaPLe
