seed: 100
treecut_generator:
    arch: treecut_generator
    dropout_rate: 0.1 # default: 0.1
data:
    name: cifar100
    loader: HierDataLoader
    data_root: prepro/raw/cifar100
    test: prepro/data/cifar100/gt_test.txt
    hierarchy: prepro/data/cifar100/tree.npy
    batch_size: 128
    n_workers: 4
    sampler:
        name: nshot
        nshot: 16
    transform: clip

# number of sampled treecuts
n_tree: 100

name: multi/seed100
